// DO NOT EDIT BY HAND — generated list of DB-touching test files.
//
// Classification rule: a test file belongs to the `db` project when its
// transitive import closure (relative, `@/`, `@ui4a/*` aliases, dynamic
// imports incl. string-const variables, vi.mock/require) reaches
// `packages/db/src/pool.ts` or bare `pg`.
// Regenerate with: node /tmp/classify-db.mjs (one-off script; this list is the
// committed artifact consumed by vitest.config.ts).
//
// Cross-checked against the TRUNCATE-text heuristic (59 files): closure is
// authoritative — it catches pool-reachable tests without literal TRUNCATE, and
// drops source-audit tests that only mention TRUNCATE in audited content.
export const dbTestFiles: readonly string[] = [
  'apps/web/src/app/.well-known/ui4a.json/route.production-auth.test.ts',
  'apps/web/src/app/.well-known/ui4a.json/route.test.ts',
  'apps/web/src/app/api/agent-runs.route.test.ts',
  'apps/web/src/app/api/chat/history/route.test.ts',
  'apps/web/src/app/api/chat/route-ai-first.test.ts',
  'apps/web/src/app/api/chat/route-audit.test.ts',
  'apps/web/src/app/api/chat/route.delegated.test.ts',
  'apps/web/src/app/api/chat/route.production-auth.test.ts',
  'apps/web/src/app/api/chat/route.step-frames.test.ts',
  'apps/web/src/app/api/chat/route.test.ts',
  'apps/web/src/app/api/chat/sessions/route.test.ts',
  'apps/web/src/app/api/contract.test.ts',
  'apps/web/src/app/api/delegations.contract.test.ts',
  'apps/web/src/app/api/delegations/route.production-auth.test.ts',
  'apps/web/src/app/api/delegations/route.test.ts',
  'apps/web/src/app/api/entity/route.production-auth.test.ts',
  'apps/web/src/app/api/entity/route.test.ts',
  'apps/web/src/app/api/entity/virtual-subjects.test.ts',
  'apps/web/src/app/api/events/route.production-auth.test.ts',
  'apps/web/src/app/api/events/route.test.ts',
  'apps/web/src/app/api/exec-plan/route.production-auth.test.ts',
  'apps/web/src/app/api/exec-plan/route.test.ts',
  'apps/web/src/app/api/exec/route.production-approval-audit.test.ts',
  'apps/web/src/app/api/exec/route.production-auth.test.ts',
  'apps/web/src/app/api/exec/route.test.ts',
  'apps/web/src/app/api/exec/route.thread.test.ts',
  'apps/web/src/app/api/health/route.test.ts',
  'apps/web/src/app/api/internal/agent-run-callback/route.test.ts',
  'apps/web/src/app/api/internal/function-callback/route.test.ts',
  'apps/web/src/app/api/meta/.well-known/ui4a.json/route.production-auth.test.ts',
  'apps/web/src/app/api/meta/.well-known/ui4a.json/route.test.ts',
  'apps/web/src/app/api/meta/drafts.contract.test.ts',
  'apps/web/src/app/api/meta/entity/route.production-auth.test.ts',
  'apps/web/src/app/api/meta/entity/route.test.ts',
  'apps/web/src/app/api/meta/exec/route.production-approval-audit.test.ts',
  'apps/web/src/app/api/meta/exec/route.production-auth.test.ts',
  'apps/web/src/app/api/meta/exec/route.test.ts',
  'apps/web/src/app/api/presence/route.rate-limit.test.ts',
  'apps/web/src/app/api/presence/route.test.ts',
  'apps/web/src/app/api/presentation/route.production-auth.test.ts',
  'apps/web/src/app/api/presentation/route.test.ts',
  'apps/web/src/app/api/presentation/sidecar/route.production-auth.test.ts',
  'apps/web/src/app/api/presentation/sidecar/route.test.ts',
  'apps/web/src/app/ready/route.test.ts',
  'apps/web/src/auth/single-process-browser-production.test.ts',
  'packages/db/src/agent-definitions/agent-definitions.test.ts',
  'packages/db/src/agent-runs.test.ts',
  'packages/db/src/drafts.test.ts',
  'packages/db/src/events.test.ts',
  'packages/db/src/function-receipts.test.ts',
  'packages/db/src/migrations.test.ts',
  'packages/db/src/pg.test.ts',
  'packages/db/src/presence/presence.rate-limit.test.ts',
  'packages/db/src/presence/presence.test.ts',
  'packages/db/src/presentation.test.ts',
  'packages/db/src/production-pool.test.ts',
  'packages/db/src/recovery.test.ts',
  'packages/db/src/replay.test.ts',
  'apps/web/src/engine/agent-run-dispatch.test.ts',
  'apps/web/src/engine/agent/agent-definition-authoring.test.ts',
  'apps/web/src/engine/agent/agent-definitions.test.ts',
  'apps/web/src/engine/agent/agent-runs.test.ts',
  'apps/web/src/engine/agent/native-agent-dispatch.test.ts',
  'apps/web/src/engine/chat-situation.test.ts',
  'apps/web/src/engine/drafts/drafts.test.ts',
  'apps/web/src/engine/human-agent-parity.test.ts',
  'apps/web/src/engine/presentation/runtime-authorization-migration.test.ts',
  'apps/web/src/engine/presentation/runtime.test.ts',
  'apps/web/src/engine/situation-consumers.test.ts',
  'apps/web/src/engine/service-tests/service.bornversion.test.ts',
  'apps/web/src/engine/service-tests/service.confirmation.test.ts',
  'apps/web/src/engine/service-tests/service.definition-versions.test.ts',
  'apps/web/src/engine/service-tests/service.definitions.test.ts',
  'apps/web/src/engine/service-tests/service.incremental-gap.test.ts',
  'apps/web/src/engine/service-tests/service.incremental.test.ts',
  'apps/web/src/engine/service-tests/service.meta.test.ts',
  'apps/web/src/engine/service-tests/service.notify.integration.test.ts',
  'apps/web/src/engine/service-tests/service.production-db.test.ts',
  'apps/web/src/engine/service-tests/service.render.test.ts',
  'apps/web/src/engine/service-tests/service.restart-replay.test.ts',
  'apps/web/src/engine/service-tests/service.test.ts',
  'apps/web/src/engine/service-tests/service.thread.test.ts',
  'apps/web/src/readiness/readiness.test.ts',
  'apps/web/src/temporal/notify.test.ts',
  'apps/worker/src/activities.production-auth.test.ts',
  'apps/worker/src/activities.test.ts',
  'apps/worker/src/agents/coding/adapter.real.test.ts',
  'apps/worker/src/agents/coding/adapter.test.ts',
  'apps/worker/src/agents/writing/adapter.test.ts',
  'apps/web/src/engine/service-tests/delegation.kill.integration.test.ts',
  'apps/worker/src/worker-db.test.ts',
];
