import {
  canonicalConfigMount,
  canonicalRuntimeEnvironment,
  canonicalSecretMount,
  dependencies,
  edgeRoutingFile,
  health,
  hostRunnerConfigRoot,
  postgresBootstrapCommand,
  postgresTlsCommand,
  runnerConfigRoot,
  runtimeConfigReadOnlyVolume,
  runtimeConfigRoot,
  runtimeService,
  runtimeTmpfs,
  stateSecretMount,
  temporalNamespaceCommand,
  temporalSchemaCommand,
  temporalServerCommand,
} from './compose-shared';
import type { ComposeRenderInput, ComposeService } from './compose-types';

export function composeServices(input: ComposeRenderInput): Record<string, ComposeService> {
  const { images } = input;
  const ui4aHost = new URL(input.edge.webPublicOrigin).hostname;
  const keycloakHost = new URL(input.edge.keycloakPublicOrigin).hostname;
  const runnerOrigins = JSON.stringify({
    'compose-container-runner': `https://${ui4aHost}:8443`,
    'compose-host-runner': `https://${ui4aHost}:9444`,
  });

  return {
    postgres: {
      image: images.postgres,
      pull_policy: 'missing',
      restart: 'unless-stopped',
      depends_on: dependencies({ 'pki-init': 'service_completed_successfully' }),
      healthcheck: health(['CMD-SHELL', 'pg_isready -U postgres -d postgres']),
      environment: {
        POSTGRES_USER: 'postgres',
        POSTGRES_DB: 'postgres',
        POSTGRES_PASSWORD_FILE: '/run/secrets/postgres-bootstrap-password',
      },
      secrets: [stateSecretMount('postgres-bootstrap-password')],
      entrypoint: ['/bin/sh', '-ec'],
      command: [postgresTlsCommand],
      tmpfs: ['/var/run/ui4a/postgres-tls:rw,noexec,nosuid,size=1m,mode=0700'],
      volumes: [
        'postgres-data:/var/lib/postgresql/data',
        'backup-data:/backups',
        'experiment-ca:/var/lib/ui4a/ca:ro',
      ],
    },
    'postgres-bootstrap': {
      image: images.postgres,
      pull_policy: 'missing',
      restart: 'no',
      depends_on: dependencies({ postgres: 'service_healthy' }),
      environment: {
        PGHOST: 'postgres',
        PGDATABASE: 'postgres',
        PGUSER: 'postgres',
        PGPASSWORD_FILE: '/run/secrets/postgres-bootstrap-password',
      },
      secrets: [
        stateSecretMount('postgres-bootstrap-password'),
        stateSecretMount('ui4a-migration-password'),
        stateSecretMount('ui4a-runtime-password'),
        stateSecretMount('keycloak-database-password'),
        stateSecretMount('temporal-schema-password'),
        stateSecretMount('temporal-runtime-password'),
        stateSecretMount('postgres-backup-password'),
      ],
      entrypoint: ['/bin/sh', '-ec'],
      command: [postgresBootstrapCommand],
      volumes: ['../postgres/bootstrap-roles.sql:/opt/ui4a/bootstrap-roles.sql:ro'],
    },
    'temporal-schema': {
      image: images.temporalAdminTools,
      pull_policy: 'missing',
      restart: 'no',
      depends_on: dependencies({
        'config-init': 'service_completed_successfully',
        'postgres-bootstrap': 'service_completed_successfully',
      }),
      entrypoint: ['/bin/sh', '-ec'],
      command: [temporalSchemaCommand],
      volumes: [runtimeConfigReadOnlyVolume],
    },
    temporal: {
      image: images.temporal,
      pull_policy: 'missing',
      restart: 'unless-stopped',
      depends_on: dependencies({
        'config-init': 'service_completed_successfully',
        'temporal-schema': 'service_completed_successfully',
      }),
      configs: [
        {
          source: 'temporal-static-config',
          target: '/etc/temporal/config/docker.yaml',
          mode: 0o444,
        },
        {
          source: 'temporal-dynamic-config',
          target: '/etc/temporal/dynamicconfig/docker.yaml',
          mode: 0o444,
        },
      ],
      entrypoint: ['/bin/sh', '-ec'],
      command: [temporalServerCommand],
      volumes: [runtimeConfigReadOnlyVolume],
      healthcheck: health(['CMD', 'nc', '-z', '127.0.0.1', '7233']),
    },
    'temporal-namespace': {
      image: images.temporalAdminTools,
      pull_policy: 'missing',
      restart: 'no',
      depends_on: dependencies({ temporal: 'service_healthy' }),
      network_mode: 'service:temporal',
      entrypoint: ['/bin/sh', '-ec'],
      command: [temporalNamespaceCommand],
    },
    'temporal-ui': {
      image: images.temporalUi,
      pull_policy: 'missing',
      restart: 'unless-stopped',
      depends_on: dependencies({ temporal: 'service_healthy' }),
      healthcheck: health(['CMD', 'wget', '-q', '--spider', 'http://127.0.0.1:8080/']),
    },
    keycloak: {
      image: images.keycloak,
      pull_policy: 'missing',
      restart: 'unless-stopped',
      depends_on: dependencies({
        'config-init': 'service_completed_successfully',
        'postgres-bootstrap': 'service_completed_successfully',
        'pki-init': 'service_completed_successfully',
      }),
      environment: {
        KC_DB: 'postgres',
        KC_DB_URL_HOST: 'postgres',
        KC_DB_URL_DATABASE: 'keycloak',
        KC_DB_USERNAME: 'keycloak_runtime',
        KC_HEALTH_ENABLED: 'true',
        KC_HTTP_ENABLED: 'true',
        KC_PROXY_HEADERS: 'xforwarded',
        KC_HOSTNAME: input.edge.keycloakPublicOrigin,
      },
      entrypoint: ['/bin/bash', '-ec'],
      command: [
        'export KC_DB_PASSWORD="$$(cat /var/run/ui4a/runtime-config/keycloak-database-password)"; export KC_BOOTSTRAP_ADMIN_USERNAME=ui4a-bootstrap; export KC_BOOTSTRAP_ADMIN_PASSWORD="$$(cat /var/run/ui4a/runtime-config/keycloak-bootstrap-admin-password)"; exec /opt/keycloak/bin/kc.sh start',
      ],
      volumes: [runtimeConfigReadOnlyVolume],
      healthcheck: health([
        'CMD-SHELL',
        "exec 3<>/dev/tcp/127.0.0.1/9000; printf 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3; grep -q '200 OK' <&3",
      ]),
    },
    'config-init': runtimeService(images.worker, 'no', {
      user: '0:0',
      environment: {},
      configs: [
        {
          source: 'ui4a-config-init',
          target: '/opt/ui4a/config-init.mjs',
          mode: 0o444,
        },
        { ...canonicalConfigMount },
      ],
      secrets: [
        { ...canonicalSecretMount },
        stateSecretMount('capability-callback-token'),
        stateSecretMount('temporal-schema-password'),
        stateSecretMount('temporal-runtime-password'),
        stateSecretMount('keycloak-database-password'),
        stateSecretMount('keycloak-bootstrap-admin-password'),
      ],
      volumes: [
        `runtime-config:${runtimeConfigRoot}`,
        `runner-config:${runnerConfigRoot}`,
        `host-runner-config:${hostRunnerConfigRoot}`,
      ],
      command: ['node', '/opt/ui4a/config-init.mjs'],
    }),
    'realm-bootstrap': runtimeService(images.worker, 'no', {
      depends_on: dependencies({
        'config-init': 'service_completed_successfully',
        keycloak: 'service_healthy',
        edge: 'service_healthy',
      }),
      environment: {
        ...canonicalRuntimeEnvironment,
        UI4A_REALM_IMPORT_FILE: '/opt/ui4a/realm-import.json',
        UI4A_KEYCLOAK_ADMIN_ORIGIN: `https://${keycloakHost}:9443`,
      },
      command: ['node', 'dist/t22-keycloak-realm-bootstrap.js', '--apply'],
      volumes: [
        'realm-data:/var/lib/ui4a/realm',
        'experiment-ca:/var/lib/ui4a/ca:ro',
        `${input.realmFile}:/opt/ui4a/realm-import.json:ro`,
        runtimeConfigReadOnlyVolume,
      ],
    }),
    migration: runtimeService(images.worker, 'no', {
      depends_on: dependencies({
        'config-init': 'service_completed_successfully',
        'postgres-bootstrap': 'service_completed_successfully',
        'pki-init': 'service_completed_successfully',
      }),
      command: ['node', 'dist/t22-migrate.js'],
      volumes: ['experiment-ca:/var/lib/ui4a/ca:ro', runtimeConfigReadOnlyVolume],
    }),
    'pki-init': runtimeService(images.runner, 'no', {
      user: '0:0',
      environment: {
        UI4A_DEPLOYMENT_PROFILE: 'production',
        UI4A_DEPLOYMENT_SETTINGS_FILE: '/run/ui4a/settings.json',
        UI4A_DEPLOYMENT_SECRETS_FILE: '/run/secrets/ui4a-deployment-secrets',
        UI4A_PKI_ROOT: '/var/lib/ui4a/ca',
        UI4A_HOST: ui4aHost,
        KEYCLOAK_HOST: keycloakHost,
        UI4A_POSTGRES_HOST: 'postgres',
      },
      command: ['node', 'dist/main.js', 'pki-init'],
      configs: [{ ...canonicalConfigMount }],
      secrets: [{ ...canonicalSecretMount }],
      volumes: ['experiment-ca:/var/lib/ui4a/ca'],
    }),
    web: runtimeService(images.web, 'unless-stopped', {
      depends_on: dependencies({
        'config-init': 'service_completed_successfully',
        'pki-init': 'service_completed_successfully',
        migration: 'service_completed_successfully',
        'realm-bootstrap': 'service_completed_successfully',
        'temporal-namespace': 'service_completed_successfully',
      }),
      environment: {
        ...canonicalRuntimeEnvironment,
        UI4A_CAPABILITY_CALLBACK_TOKEN_FILE: `${runtimeConfigRoot}/capability-callback-token`,
      },
      healthcheck: health([
        'CMD',
        'node',
        '-e',
        "fetch('http://127.0.0.1:3100/ready').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))",
      ]),
      volumes: ['experiment-ca:/var/lib/ui4a/ca:ro', runtimeConfigReadOnlyVolume],
    }),
    worker: runtimeService(images.worker, 'unless-stopped', {
      depends_on: dependencies({
        'config-init': 'service_completed_successfully',
        migration: 'service_completed_successfully',
        'realm-bootstrap': 'service_completed_successfully',
        'temporal-namespace': 'service_completed_successfully',
        edge: 'service_healthy',
      }),
      environment: {
        ...canonicalRuntimeEnvironment,
        UI4A_PUBLIC_BASE_URL: 'http://web:3100',
        UI4A_CAPABILITY_CALLBACK_TOKEN_FILE: `${runtimeConfigRoot}/capability-callback-token`,
        UI4A_RUNNER_IMAGE: images.runner,
        UI4A_HOST_RUNNER_ORIGINS: runnerOrigins,
      },
      healthcheck: health([
        'CMD',
        'node',
        '-e',
        "fetch('http://127.0.0.1:3101/ready').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))",
      ]),
      volumes: [
        'experiment-ca:/var/lib/ui4a/ca:ro',
        runtimeConfigReadOnlyVolume,
        'runner-workspaces:/workspaces',
      ],
    }),
    runner: runtimeService(images.runner, 'unless-stopped', {
      depends_on: dependencies({
        'config-init': 'service_completed_successfully',
        'pki-init': 'service_completed_successfully',
      }),
      environment: {
        ...canonicalRuntimeEnvironment,
        UI4A_DEPLOYMENT_SETTINGS_FILE: `${runnerConfigRoot}/settings.json`,
        UI4A_DEPLOYMENT_SECRETS_FILE: `${runnerConfigRoot}/runner-secrets.json`,
        UI4A_RUNNER_ID: 'compose-container-runner',
        UI4A_RUNNER_IMAGE: images.runner,
      },
      healthcheck: health([
        'CMD',
        'node',
        '-e',
        "fetch('http://127.0.0.1:3102/live').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))",
      ]),
      command: ['node', 'dist/main.js', 'daemon'],
      volumes: [
        'experiment-ca:/var/lib/ui4a/ca:ro',
        'runner-workspaces:/workspaces',
        'runner-artifacts:/artifacts',
        `runner-config:${runnerConfigRoot}:ro`,
      ],
    }),
    'host-runner': runtimeService(images.runner, 'unless-stopped', {
      profiles: ['host-runner'],
      depends_on: dependencies({
        'config-init': 'service_completed_successfully',
        'pki-init': 'service_completed_successfully',
      }),
      environment: {
        ...canonicalRuntimeEnvironment,
        UI4A_DEPLOYMENT_SETTINGS_FILE: `${hostRunnerConfigRoot}/settings.json`,
        UI4A_DEPLOYMENT_SECRETS_FILE: `${hostRunnerConfigRoot}/runner-secrets.json`,
        UI4A_RUNNER_ID: 'compose-host-runner',
        UI4A_RUNNER_IMAGE: images.runner,
      },
      healthcheck: health([
        'CMD',
        'node',
        '-e',
        "fetch('http://127.0.0.1:3102/live').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))",
      ]),
      command: ['node', 'dist/main.js', 'daemon'],
      volumes: [
        'experiment-ca:/var/lib/ui4a/ca:ro',
        'runner-workspaces:/workspaces',
        'runner-artifacts:/artifacts',
        `host-runner-config:${hostRunnerConfigRoot}:ro`,
      ],
    }),
    edge: {
      image: images.edge,
      pull_policy: 'missing',
      restart: 'unless-stopped',
      user: '1000:1000',
      read_only: true,
      tmpfs: [runtimeTmpfs],
      depends_on: dependencies({
        'pki-init': 'service_completed_successfully',
      }),
      healthcheck: health([
        'CMD',
        'wget',
        '-q',
        '--no-check-certificate',
        '--spider',
        'https://127.0.0.1:8443/_edge_live',
      ]),
      environment: {
        UI4A_HOST: ui4aHost,
        KEYCLOAK_HOST: keycloakHost,
        HOME: '/tmp',
        XDG_CONFIG_HOME: '/tmp/caddy-config',
        XDG_DATA_HOME: '/tmp/caddy-data',
      },
      volumes: ['experiment-ca:/var/lib/ui4a/ca:ro', `${edgeRoutingFile}:/etc/caddy/Caddyfile:ro`],
      ports: [`127.0.0.1:${input.edge.publishedPort}:8443`],
      networks: {
        default: {
          aliases: [ui4aHost, keycloakHost],
        },
      },
      command: ['caddy', 'run', '--config', '/etc/caddy/Caddyfile'],
    },
  };
}
