apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ui4a-runtime-jobs
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "ui4a.labels" . | nindent 4 }}
rules:
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, get, list, watch, delete]
  - apiGroups: ['']
    resources: [pods, pods/log]
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ui4a-runtime-jobs
  namespace: {{ .Values.namespace.name | quote }}
  labels:
    {{- include "ui4a.labels" . | nindent 4 }}
subjects:
  {{- range $serviceAccount := .Values.serviceAccounts }}
  - kind: ServiceAccount
    name: {{ $serviceAccount | quote }}
    namespace: {{ $.Values.namespace.name | quote }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ui4a-runtime-jobs
