apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Values.namespace.name | quote }}
spec:
  selector: { app.kubernetes.io/name: postgres, app.kubernetes.io/instance: ui4a }
  ports:
    - { name: postgres, port: 5432, targetPort: 5432 }
---
apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: {{ .Values.namespace.name | quote }}
spec:
  selector: { app.kubernetes.io/name: temporal, app.kubernetes.io/instance: ui4a }
  ports:
    - { name: grpc, port: 7233, targetPort: 7233 }
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
  namespace: {{ .Values.namespace.name | quote }}
spec:
  selector: { app.kubernetes.io/name: temporal-ui, app.kubernetes.io/instance: ui4a }
  ports:
    - { name: http, port: 8080, targetPort: 8080 }
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.namespace.name | quote }}
spec:
  selector: { app.kubernetes.io/name: keycloak, app.kubernetes.io/instance: ui4a }
  ports:
    - { name: http, port: 8080, targetPort: 8080 }
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Values.namespace.name | quote }}
spec:
  selector: { app.kubernetes.io/name: web, app.kubernetes.io/instance: ui4a }
  ports:
    - { name: http, port: 3100, targetPort: 3100 }
---
apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: {{ .Values.namespace.name | quote }}
spec:
  selector: { app.kubernetes.io/name: worker, app.kubernetes.io/instance: ui4a }
  ports:
    - { name: http, port: 3101, targetPort: 3101 }
